[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Please configure services individually'"

# Backend service
[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "pip install -r requirements.txt"

[services.deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.variables]
ENVIRONMENT = "production"

# Frontend service  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npm start"

[services.variables]
NEXT_PUBLIC_API_BASE_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"